In [1]:
import pandas as pd
import numpy as np

In [2]:
# Load csv
spotify_csv = "../Data/top10KaggleData.csv"
#  convert to df
# had trouble loading and fixed based on this from stack overflow: https://stackoverflow.com/questions/46000191/utf-8-codec-cant-decode-byte-0x92-in-position-18-invalid-start-byte
spotify_df= pd.read_csv(spotify_csv, sep=",", encoding='cp1252')

In [3]:
# check head
spotify_df.head()

,Unnamed: 0,title,artist,top genre,year,bpm,nrgy,dnce,dB,live,val,dur,acous,spch,pop
0,1,"Hey, Soul Sister",Train,neo mellow,2010,97,89,67,-4,8,80,217,19,4,83
1,2,Love The Way You Lie,Eminem,detroit hip hop,2010,87,93,75,-5,52,64,263,24,23,82
2,3,TiK ToK,Kesha,dance pop,2010,120,84,76,-3,29,71,200,10,14,80
3,4,Bad Romance,Lady Gaga,dance pop,2010,119,92,70,-4,8,71,295,0,4,79
4,5,Just the Way You Are,Bruno Mars,pop,2010,109,84,64,-5,9,43,221,2,4,78

In [4]:
# check tail
spotify_df.tail()

,Unnamed: 0,title,artist,top genre,year,bpm,nrgy,dnce,dB,live,val,dur,acous,spch,pop
597,599,Find U Again (feat. Camila Cabello),Mark Ronson,dance pop,2019,104,66,61,-7,20,16,176,1,3,75
598,600,Cross Me (feat. Chance the Rapper & PnB Rock),Ed Sheeran,pop,2019,95,79,75,-6,7,61,206,21,12,75
599,601,"No Brainer (feat. Justin Bieber, Chance the Ra...",DJ Khaled,dance pop,2019,136,76,53,-5,9,65,260,7,34,70
600,602,Nothing Breaks Like a Heart (feat. Miley Cyrus),Mark Ronson,dance pop,2019,114,79,60,-6,42,24,217,1,7,69
601,603,Kills You Slowly,The Chainsmokers,electropop,2019,150,44,70,-9,13,23,213,6,6,67

In [5]:
# remove unamed column:
# spotify_df = spotify_df[['title', 'artist', 'top genre', 'year', 'bpm', 'nrgy', 'dnce', 'dB', 'live', 'val', 'dur', 'acous', 'spch', 'pop']]
# spotify_df.head()

In [6]:
# rename columns
spotify_df = spotify_df.rename(columns={'Unnamed: 0': 'index','top genre': 'top_genre','nrgy': 'energy', 'dnce':'dancability', 'val': 'valence', 'dur': 'duration_in_seconds', 'acous': 'acousticness', 'spch': 'speechiness', 'pop':'popularity'})
spotify_df.head()

,index,title,artist,top_genre,year,bpm,energy,dancability,dB,live,valence,duration_in_seconds,acousticness,speechiness,popularity
0,1,"Hey, Soul Sister",Train,neo mellow,2010,97,89,67,-4,8,80,217,19,4,83
1,2,Love The Way You Lie,Eminem,detroit hip hop,2010,87,93,75,-5,52,64,263,24,23,82
2,3,TiK ToK,Kesha,dance pop,2010,120,84,76,-3,29,71,200,10,14,80
3,4,Bad Romance,Lady Gaga,dance pop,2010,119,92,70,-4,8,71,295,0,4,79
4,5,Just the Way You Are,Bruno Mars,pop,2010,109,84,64,-5,9,43,221,2,4,78

In [7]:
# check data types - notate for SQl load
spotify_df.dtypes

index                   int64
title                  object
artist                 object
top_genre              object
year                    int64
bpm                     int64
energy                  int64
dancability             int64
dB                      int64
live                    int64
valence                 int64
duration_in_seconds     int64
acousticness            int64
speechiness             int64
popularity              int64
dtype: object

In [8]:
# check for and replace and NAN values (SQL will not read in NAN)
# https://stackoverflow.com/questions/27159189/find-empty-or-nan-entry-in-pandas-dataframe
spotify_df[ (spotify_df['title'].notnull()) & (spotify_df['title']!=u'') ].index

Int64Index([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
            ...
            592, 593, 594, 595, 596, 597, 598, 599, 600, 601],
           dtype='int64', length=602)

In [9]:
spotify_df.head()

,index,title,artist,top_genre,year,bpm,energy,dancability,dB,live,valence,duration_in_seconds,acousticness,speechiness,popularity
0,1,"Hey, Soul Sister",Train,neo mellow,2010,97,89,67,-4,8,80,217,19,4,83
1,2,Love The Way You Lie,Eminem,detroit hip hop,2010,87,93,75,-5,52,64,263,24,23,82
2,3,TiK ToK,Kesha,dance pop,2010,120,84,76,-3,29,71,200,10,14,80
3,4,Bad Romance,Lady Gaga,dance pop,2010,119,92,70,-4,8,71,295,0,4,79
4,5,Just the Way You Are,Bruno Mars,pop,2010,109,84,64,-5,9,43,221,2,4,78

In [10]:
spotify_df.tail()

,index,title,artist,top_genre,year,bpm,energy,dancability,dB,live,valence,duration_in_seconds,acousticness,speechiness,popularity
597,599,Find U Again (feat. Camila Cabello),Mark Ronson,dance pop,2019,104,66,61,-7,20,16,176,1,3,75
598,600,Cross Me (feat. Chance the Rapper & PnB Rock),Ed Sheeran,pop,2019,95,79,75,-6,7,61,206,21,12,75
599,601,"No Brainer (feat. Justin Bieber, Chance the Ra...",DJ Khaled,dance pop,2019,136,76,53,-5,9,65,260,7,34,70
600,602,Nothing Breaks Like a Heart (feat. Miley Cyrus),Mark Ronson,dance pop,2019,114,79,60,-6,42,24,217,1,7,69
601,603,Kills You Slowly,The Chainsmokers,electropop,2019,150,44,70,-9,13,23,213,6,6,67

In [11]:
# find unique names in genre
spotify_df.top_genre.unique()

array(['neo mellow', 'detroit hip hop', 'dance pop', 'pop',
       'canadian pop', 'hip pop', 'barbadian pop', 'atl hip hop',
       'australian pop', 'indie pop', 'art pop', 'colombian pop',
       'big room', 'british soul', 'chicago rap', 'acoustic pop',
       'permanent wave', 'boy band', 'baroque pop', 'celtic rock',
       'electro', 'complextro', 'canadian hip hop', 'candy pop',
       'alaska indie', 'folk-pop', 'metropopolis', 'house',
       'australian hip hop', 'electropop', 'australian dance',
       'hollywood', 'canadian contemporary r&b',
       'irish singer-songwriter', 'tropical house', 'belgian edm',
       'french indie pop', 'hip hop', 'danish pop', 'latin',
       'canadian latin', 'electronic trap', 'edm', 'electro house',
       'downtempo', 'brostep', 'contemporary country', 'moroccan pop',
       'escape room', 'alternative r&b'], dtype=object)

In [12]:
# update genres to have more concise options when loading into dashboard
spotify_df['top_genre'] = spotify_df['top_genre'].replace({'neo mellow': 'pop',"detriot hip hop": 'hip hop', 'dance pop': 'pop', 'canadian pop': 'pop', 'barbadian pop': 'pop', 'atl hip hop': 'hip hop', 'australian pop': 'pop', 'indie pop': 'indie','art pop': 'pop','colombian pop': 'pop', 'big room': 'dance/edm','british soul': 'pop', 'chicago rap': "rap", 'acoustic pop': 'pop', 'permanent wave': 'pop', 'boy band':'pop','baroque pop': 'pop','celtic rock': 'rock', 'electro': 'dance/edm','complextro':'pop', 'canadian hip hop': 'hip hop', 'candy pop': 'pop','alaska indie': 'indie', 'folk-pop': 'indie', 'metropopolis': 'indie', 'house':'pop','australian hip hop': 'hip hop', 'electropop':'pop', 'australian dance': 'dance/edm', 'hollywood':"pop",'canadian contemporary r&b': 'R&B','irish singer-songwriter': 'indie', 'tropical house':'dance/edm', 'belgian edm': 'dance/edm', 'french indie pop': 'indie','danish pop': 'pop', 'canadian latin': 'pop', 'electronic trap':'dance/edm','electro house': 'dance/edm','downtempo': 'dance/edm', 'brostep': 'dance/edm', 'contemporary country': 'country', 'moroccan pop': 'latin', 'escape room': 'pop', 'alternative r&b':"R&B", 'detroit hip hop':'hip hop', 'hip pop': 'R&B','edm': 'dance/edm' })

In [13]:
# find unique names in genre
spotify_df.top_genre.unique()

array(['pop', 'hip hop', 'R&B', 'indie', 'dance/edm', 'rap', 'rock',
       'latin', 'country'], dtype=object)

In [14]:
spotify_df.top_genre.unique()

array(['pop', 'hip hop', 'R&B', 'indie', 'dance/edm', 'rap', 'rock',
       'latin', 'country'], dtype=object)

In [15]:
# # create columns of unique identifier to make as primary key in sql
# # https://cmdlinetips.com/2018/11/how-to-join-two-text-columns-into-a-single-column-in-pandas/
# spotify_df ['title_artist'] = spotify_df["title"] +" "+ spotify_df["artist"]

# # reorder columsn so new one is first:
# spotify_df = spotify_df[['title_artist','title', 'artist', 'top_genre', 'year', 'bpm', 'energy', 'dancability', 'dB', 'live', 'valence', 'duration_in_seconds', 'acousticness', 'speechiness', 'popularity']]
# spotify_df.head()

In [16]:
# export into csv

spotify_df.to_csv("../Data/kagglesongs.csv", encoding="utf-8", index=False)